
spring:
  datasource:
    url: jdbc:h2:mem:devdb
    username: dev
    password: password
  jpa:
    # Сначала hibernate делает инициализацию потом вставку из data.sql
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855